### ISSUE TITLE
HTTPS voor aanspreken services

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/CDS-Assembly#19]
VRN services dienen aangesproken te kunnen worden via HTTPS.

**Comment by stefanvanwouw** [comment]
In de acceptatieomgeving zit er een https gateway voor. Dus we krijgen "gratis" https zonder extra configuratie.

**Comment by reinoldp** [comment]
kan deze issue gesloten worden?

**Comment by stefanvanwouw** [comment]
wat mij betreft wel. Op acc hebben we https.
