### ISSUE TITLE
Database wordt overschreven bij update van PostgreSQL image

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/CDS-Assembly#20]
Bij een update van het PostgreSQL image wordt de database in het daarvoor bestemde volume overschreven.

Uitzoeken waarom dit gebeurt en oplossen: dit is niet wenselijk, aangezien de bestaande data bewaard moet blijven bij een update.

**Comment by stefanvanwouw** [comment]
Hier is ook iets te vinden over data-only containers: http://docs.docker.com/userguide/dockervolumes/ Misschien is dat een idee (volgensmij gebruiken we dat nu niet?) , ook makkelijk te backuppen.

**Comment by stefanvanwouw** [comment]
Dit is waarschijnlijk de issue. Kan verholpen worden door data-only container te gebruiken.
"There are a couple of issues with using volumes in certain scenarios:

    Volumes are container specific, when you create a new container, even with the same image, you do not have access to the data.
    Since image layers are built using containers, data saved to folders which have been specified as a volume does not make it to the next layer, or your final container

If you want data to persist between updated containers you have to manually map data to the host outside the normal, container-specific mount points."

http://www.tech-d.net/2013/12/16/persistent-volumes-with-docker-container-as-volume-pattern/

**Comment by erikorbons** [comment]
De database zit in een data-only container, maak ik zal bovenstaande punten nog even meenemen in mijn analyse van het probleem.

**Comment by stefanvanwouw** [comment]
Na veel research weet ik waarschijnlijk hoe het komt:

- We hebben een (extern) data only volume in /var/lib/postgresql . In deze dir staat de database data.
- We hebben een cds-postgresql image met een aantal psql commando's die database data aanmaken in het cds-postgres image volume (ook in /var/lib/postgresql, maar dan in de image ipv extern data only volume).

Op het moment dat een container wordt gestart wordt de content van een image volume naar de externe data only volume gekopieerd bij overeenkomstige paden (dit is het geval: /var/lib/postgresql).  De initieële data in ons cds-postgresql image overschrijft dus de database data in het externe data only volume.

Oplossingsrichting: Geen initieële database populatie in het cds-postgresql image. Ik kan bijvoorbeeld een apart cds-postgresql-init container maken die we slechts eenmalig draaien om het data-only volume te populaten. Voor de LDAP zelfde soort aanpak.

Wat denk je hiervan @erikorbons ?

**Comment by stefanvanwouw** [comment]
Een andere oplossingsrichting is om een wrapper om het postgresql daemon start commando te maken in CMD en daar afhankelijk van het wel of niet bestaan van database data het ofwel te initialiseren, ofwel te updaten met nieuwe structuur van een nieuwe VRN versie. Deze aanpak ga ik eerst uitproberen.
