### ISSUE TITLE
Updateprocedure LDAP

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/CDS-Assembly#24]
In navolging van de discussie in #23 en CDS-VRN/InSpider#42

**Comment by stefanvanwouw** [comment]
Het is mogelijk om met LDIF files wijzigingen aan te brengen in de LDAP database: http://www.zytrax.com/books/ldap/ch8/#changetype

**Comment by erikorbons** [comment]
Ik zie zo snel niet hoe de benodigde wijzigingen in LDAP met een statische LDIF gedaan kunnen worden, aangezien de wijziging afhankelijk is van een query-resultaat: alle bestaande gebruikers moeten aan een nieuwe groep worden toegekend. Wellicht zijn er mensen met meer verstand van LDAP (@reinoldp ?) die mij uit de brand kunnen helpen, maar het lijkt er op dat dit alleen mogelijk is in combinatie met (bijvoorbeeld) een shell-script.

**Comment by erikorbons** [comment]
Vanochtend tijdens de standup is besloten om dit even te parkeren. Er is een instructie om LDAP bij te werken en het ontwikkelen en testen van een automatische updateprocedure vergt op dit punt te veel tijd.
