### ISSUE TITLE
Release 2.2-vrn-0.4.1 maken en uitrollen op acc

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/CDS-Assembly#27]

**Comment by stefanvanwouw** [comment]
Buildserver stuk, dus ik doe het nu vanaf mn laptop.

**Comment by annesongithub** [comment]
Is er niemand met wat maven kennis die je kan helpen het te fixen?

**Comment by stefanvanwouw** [comment]
Nexus geeft HTTP 500 terug voor alles nu. Is een known issue (al Jan Boonen e.d. over gemaild). Maar dit releasen via laptop gaat prima. Naar Nexus pushen deed de buildserver toch al niet goed.
